# starts application on a random port
server:
  port: 0

spring:
  application:
    name: ProductsMicroservice
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094, localhost:9096
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

kafka:
  topic:
    name: product-created-events-topic
    partitions: 3
    replicas: 3
    min-insync-replicas: 2
